### ISSUE TITLE
How to use uptide

### ISSUE THREAD

**Issue by nanmohae** [stephankramer/uptide#5]
Hello Stephan,

Great job creating this package! I think it can be of great use in my research. Do you have any short documentation on how to use uptide? I see the code but it is hard to figure out where to start from.

Thanks!

Jeong

**Comment by acrosby** [comment]
I have tidal elevations working, but it is unclear to me if velocities are supported yet...

**Comment by stephankramer** [comment]
@nanmohae : I've added a little bit more explanation in the README.md. Feel free to ask if anything is still unclear. Contributions to the documentation are always welcome :-)

@acrosby: There is no support for reconstructing velocities from either TPXO or FES at the moment. I'm am planning to add it indeed. See #8
